apiVersion: v1
kind: Service
metadata:
  name: status-app
  namespace: monitoring
  labels:
    app: status-app
spec:
  type: ClusterIP
  selector:
    app: status-app
  ports:
    - name: http
      port: 8000
      targetPort: http
